#!/bin/sh

chown tomcat7:tomcat7 /var/app/${PACKAGE}/webapps
chown tomcat7:adm /var/cache/${PACKAGE}
chgrp tomcat7 /etc/${PACKAGE}/Standalone
chmod 775 /etc/${PACKAGE}/Standalone

ln -s /etc/init.d/oh-tomcat-app /etc/init.d/${PACKAGE}
ln -s /var/log/${PACKAGE} /var/app/${PACKAGE}/logs
ln -s /etc/${PACKAGE} /var/app/${PACKAGE}/conf
ln -s /var/lib/tomcat7/conf/web.xml /etc/${PACKAGE}/web.xml
ln -s /var/cache/${PACKAGE} /var/app/${PACKAGE}/work
